### ISSUE TITLE
Should the whitepaper link to specific coins? Which ones?

### ISSUE THREAD

**Issue by ripper234** [DavidAJohnston/TheValueofAppCoins#7]
Is it scalable to link to particular coins?
What if you get 50 pull requests from people who want you to add their coins?
How do you manage that? What about a due dilligance process?

This is why I think the whitepaper should not try and manage this list, but rather only link to the reddit.

See #6

**Comment by DavidAJohnston** [comment]
I think having specific App Coin references makes the paper more powerful. I've added the link you created and cleaned things up a bit.

**Comment by ripper234** [comment]
Aren't you considered of the legal/P.R risk that happens if one of these coins turns out to be a scam?
What is the plan to integrate future pull requests that add more coins? How will the vetting happen?

**Comment by taariq** [comment]
@ripper234 curate as you go. The github repo is not a scam, just a documented site of Appcoins. If one of them turns out to be a scam or fails miserably, then you'll want to create a section for failed coins and move those to that section. This repo and its documentation is just an information resource, not a company.

**Comment by ripper234** [comment]
Well, if David/BitAngels want to curate that, sure.
As long as it's not my headache :)
